### ISSUE TITLE
The color of canvas item light looks different compared to Lumi Lights block light

### ISSUE THREAD

**Issue by spiralhalo** [spiralhalo/LumiLights#17]
Default canvas torch color looks more yellow compared to Lumi Lights block color.

**Comment by supsm** [comment]
![2020-12-13_12 14 11](https://user-images.githubusercontent.com/60897356/102022612-d6711780-3d3c-11eb-91c4-b36a6c053d67.png)
![2020-12-13_12 14 23](https://user-images.githubusercontent.com/60897356/102022613-d709ae00-3d3c-11eb-94db-45116a540d08.png)

**Comment by spiralhalo** [comment]
Should be good now. Affects glowstone, jack o lantern, lantern, shroomlight, and torch.
![image](https://user-images.githubusercontent.com/8444172/102140026-42fd2b00-3e91-11eb-8c5b-3a42d1a64a33.png)
![image](https://user-images.githubusercontent.com/8444172/102140036-455f8500-3e91-11eb-827f-165cc0e305cf.png)

**Comment by supsm** [comment]
Dangit, I wasted my time doing this... https://github.com/supsm/LumiLights
might be more accurate though... unsure
