### ISSUE TITLE
Surface disappearing when placing a block

### ISSUE THREAD

**Issue by tyra314** [spiralhalo/LumiLights#33]
Hey, I discovered this when I tried to fortune my coal ores:

When you jump and place a block at a large height then the ground starts to disappear. The effect gets progressively worse with height.

![2021-02-14_18 29 10](https://user-images.githubusercontent.com/16997177/107884145-80af1c00-6ef3-11eb-86c6-2dde6a3e0da9.jpg)

![2021-02-14_18 33 49](https://user-images.githubusercontent.com/16997177/107884131-58bfb880-6ef3-11eb-8e2e-3dbe355830f8.png)

I'm running:
- Minecraft 1.16.5
- Canvas 1.0.1267
- LumiLights 0.14
- PBRExt 0.7
- PBRCompat 0.6

**Comment by supsm** [comment]
This is a canvas issue, consider putting this on [canvas](https://github.com/grondag/canvas/issues) instead (if it hasn't already been opened, of course)

**Comment by spiralhalo** [comment]
I think this is related to Canvas issue https://github.com/grondag/canvas/issues/185. Feel free to add more information/examples on that issue instead.
