### ISSUE TITLE
Latest version producing minimal effects

### ISSUE THREAD

**Issue by Geonaut3** [spiralhalo/LumiLights#39]
In the latest version of LumiLights (0.21) and Canvas (1.0.1267), while using Fabric API (0.32.5), Lumi Lights isn't producing any visual effects but some minor recoloring on water. I don't know if this is intended or not.

![2021-04-25_08 06 24](https://user-images.githubusercontent.com/83167515/115992879-f2fc4680-a59d-11eb-8074-6b1ea9557af7.png)

**Comment by spiralhalo** [comment]
Canvas 1.0.1267 isn't compatible anymore.

Consult https://spiralhalo.github.io/ for latest compatible version.

**Comment by Geonaut3** [comment]
Oh, okay.
