### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ghost** [spiralhalo/LumiLights#40]
Is there a guide about it?

**Comment by heymanMC** [comment]
https://github.com/spiralhalo/LumiLights/wiki
This is not the place to ask for help, however. It's better to ask on the discord.

**Comment by spiralhalo** [comment]
https://github.com/spiralhalo/LumiLights/wiki/How-to-use-Lumi-Lights-WIP has all the information you need.

I've also opened Discussions for people who don't use discord: https://github.com/spiralhalo/LumiLights/discussions

Please use issues for bug reports in the future.
