### ISSUE TITLE
colored dots covering screen in nether mac compat build

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#44]
colored dots cover the screen in the nether when using mac compat build.

os: macos big sur
version: 0.24 mac compat
canvas version: 1501 lts

screenshot:
![2021-05-08_12 44 05](https://user-images.githubusercontent.com/83884198/117551494-248ffb80-affb-11eb-941b-1b404fb3b23a.png)

config: 
  {
	  "lumi:aesthetics_config": {
		  "block_light_mode": "warm",
		  "bloom_intensity": 1,
		  "bloom_scale": 3,
		  "sky_bloom_intensity": 0,
		  "godrays_intensity": 0,
		  "sky_mode": "lumi",
		  "lumi_sky_color": "deep_cerulean",
		  "glint_style": "glint_a",
		  "glint_red": 0.655,
		  "glint_green": 0.333,
		  "glint_blue": 1.0,
		  "toon_outline": false,
		  "name_tag_shadow": false
	  },
	  "lumi:performance_config": {
		  "antialiasing": "none",
		  "ambient_occlusion": "vanilla",
		  "blocklight_specular_mode": "fast",
		  "reflection_profile": "none",
		  "reflection_maximum_roughness_relative": 1,
		  "reflection_on_hand": false,
		  "cloud_rendering": "parallax",
		  "volumetric_fog": false
	  },
	  "lumi:clouds_config": {
		  "parallax_cloud_altitude": 100,
		  "parallax_cloud_thickness": 40,
		  "volumetric_cloud_mode": "skybox",
		  "volumetric_cloud_denoising": false
	  },
	  "lumi:gameplay_config": {
		  "handheld_light_radius": 10,
		  "true_darkness_default": false,
		  "true_darkness_nether": false,
		  "true_darkness_end": false,
		  "true_darkness_moonlight": false
	  },
	  "lumi:fog_config": {
		  "overworld_fog_use_altitude": true,
		  "fog_far_chunks": 8,
		  "fog_density_relative": 0,
		  "underwater_fog_far_chunks": 1,
		  "underwater_fog_density_relative": 15
	  },
	  "lumi:experimental_config": {
		  "parallax_cloud_density": 1.0,
		  "volumetric_fog_softness_relative": 18,
		  "glint_mode": "shader",
		  "taa_debug_render": "off",
		  "multi_bounce_reflection": false,
		  "kaleidoskop": false,
		  "rgb_caves": false,
		  "tone_profile": "auto_exposure",
		  "rain_puddles": false,
		  "caustics_mode": "none",
		  "cloud_time": "world",
		  "overlay_debug": "none"
	  }
  }

logs: 
[latest.log](https://github.com/spiralhalo/LumiLights/files/6446461/latest.log)

**Comment by sharpenedblade** [comment]
Reproduced in canvas-mc116-configurable-pipeline-1.0.1492.jar using lumilights 0.24

**Comment by sharpenedblade** [comment]
It disappears when moving the camera with taa on

**Comment by spiralhalo** [comment]
1. Can you check `.minecraft/canvas_shader_debug/` and see if there is a `failed` folder? If so, what is the contents of that folder?
2. Does the bug occur with `Reduce resolution on Macs` option turned off? (Video Settings -> Canvas)

**Comment by sharpenedblade** [comment]
1. `.minecraft/canvas_shader_debug/` is empty

2. `Reduce resolution on Macs` set to `off` still has the bug

**Comment by spiralhalo** [comment]
The only thing I could tell is that it happens before hand rendering,, and it seems that everything is turned off except clouds. Does setting cloud mode to vanilla fix it?

**Comment by spiralhalo** [comment]
```glsl
void main()
{
    if (!frx_worldFlag(FRX_WORLD_IS_OVERWORLD)) return;
```

I think this might be the issue. Cloud returns on non-overworld and returning on `main()` is said to give "undefined" result. This seems like what an "undefined" result could be.

What I could try is writing black instead of returning.

**Comment by spiralhalo** [comment]
I've pushed the fix idea. To try it, download the repo as zip and then **extract the zip directly** into your RP folder (dont extract into another folder)

![image](https://user-images.githubusercontent.com/8444172/117562267-cf6deb80-b0c7-11eb-89b2-48ad27885331.png)

**Comment by spiralhalo** [comment]
Switch to mac compat branch before downloading.

![image](https://user-images.githubusercontent.com/8444172/117562275-e4e31580-b0c7-11eb-924e-9394e751a459.png)

**Comment by sharpenedblade** [comment]
Fixed when downloading zip from 116_mac_compat branch

**Comment by sharpenedblade** [comment]
Its back, but the overworld, and only half the screen at a time, the dots range from black to gray, and it flashes, game is flickering with half the screen getting brighter to

**Comment by sharpenedblade** [comment]
Fixed on latest commit
