### ISSUE TITLE
Extreme lag or freeze on world load or changing dimensions.

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#46]
Extreme lag for 15 seconds after world load. Does not occur with default canvas shaders. All setting set to fast or off. Stable fps after 30 sec of world load.

mods: canvas lts 1501, fapi 34.1, starlight, lithinuim, cull leaves.
jdk: Adopt open jdk openj9 16
minecraft: 1.16.5
os: macos

**Comment by sharpenedblade** [comment]
Likely occurs on windows and linux, but I do not have a pc to test on.

**Comment by sharpenedblade** [comment]
Also lags when culled chunks are rendered. To reproduce, dig a hole 16 block down, then dig forward 128 blocks. now dig up to the surface. Observer extreme lag or freeze.

**Comment by sharpenedblade** [comment]
Could be my hardware, but continuum on optifine runs at 30 fps, no lag, 5 seconds to load world

**Comment by FwuffyPetsOwO** [comment]
How did you get Lumi working on Mac?
Anyway, this is (probably) not an issue with Lumi, make sure render distance is not too high, because rendering all chunks in a 32 chunks radius with Shader is not great.

**Comment by sharpenedblade** [comment]
Render distance is 8, and I used the mac compat build.

**Comment by sharpenedblade** [comment]
It is probably lumi becuase optifine shaders on high work well at same settings.

**Comment by sharpenedblade** [comment]
I suspect chunk culling

**Comment by supsm** [comment]
How much ram have you allocated?

**Comment by sharpenedblade** [comment]
5g

**Comment by sharpenedblade** [comment]
Same thing with 6g alocated

**Comment by sharpenedblade** [comment]
Can someone test on pc with igpu

**Comment by spiralhalo** [comment]
> Extreme lag for 15 seconds after world load. Does not occur with default canvas shaders.

This might be related to volumetric clouds. I have no idea how but volumetric cloud used to cause infinite loop during world load only. Although clouds shouldn't render in other dimension at all so it shouldn't affect changing dimensions.

> All settings set to fast or off (?)

In that case it might not be clouds at all. Perhaps shadow? Have you tried comparing it to Canvas Dev (i.e. Canvas Standard but with shadows)

> Also lags when culled chunks are rendered.

Check if the bottleneck is in your gpu or cpu. Canvas occlusion culling is pretty hard on the cpu usage. As a rule of thumb Lumi Lights mostly causes gpu bottleneck (My gpu usage with Canvas Standard is ~60% vs Lumi Lights ~99%)

**Comment by sharpenedblade** [comment]
>In that case it might not be clouds at all. Perhaps shadow? Have you tried comparing it to Canvas Dev (i.e. Canvas >Standard but with shadows)

I use plain lumilights, which does not have shadows.

>Check if the bottleneck is in your gpu or cpu. Canvas occlusion culling is pretty hard on the cpu usage. As a rule of >thumb Lumi Lights mostly causes gpu bottleneck (My gpu usage with Canvas Standard is ~60% vs Lumi Lights ~99%)

I have igpu laptop, so it is likely gpu, but cpu gpu usage are never over 70%, even with browser open.

**Comment by sharpenedblade** [comment]
When testing with only minecraft running cpu idles at 125%. During lag spikes cpu is at 450%, and gpu at 0%. When playing normaly, the gpu is at around 10%.

**Comment by sharpenedblade** [comment]
The values above 100% are becuase I used activity moniter on macos, which doesnt count mutiple cores.

**Comment by sharpenedblade** [comment]
All cpu cores are evenly used

**Comment by sharpenedblade** [comment]
Did not intend to close

**Comment by sharpenedblade** [comment]
now world loads almost instant, but there is a hug lag spike when looking up for the first time

**Comment by sharpenedblade** [comment]
While this is increased by lumi, zgc, more memory to minecraft, and recent canvas updates have made it survivable
