### ISSUE TITLE
GIving effect speed 6 allows xray.

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#47]
![2021-05-13_08 59 39](https://user-images.githubusercontent.com/83884198/118153190-773a3080-b3ca-11eb-98e3-088b91eb1aa9.png)

Using speed 5 allows you to xray using quake pro fov. Speed 5 is sometimes given on servers using commands. In vanilla and canvas default, the surrounding caves are black. It also makes the game unplayable in 1 block wide corridors.

to reproduce: dig straight down 4 blocks. change fov to quake pro. do `/effect give @a minecraft:speed 10 5`. Observe you are able to xray.

**Comment by spiralhalo** [comment]
This is a vanilla issue. I don't know what else to say.
