### ISSUE TITLE
It is very bright when underwater during the night

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#49]
![2021-05-13_10 08 17](https://user-images.githubusercontent.com/83884198/118160566-50342c80-b3d3-11eb-88e1-a06291f10b49.png)

**Comment by sharpenedblade** [comment]
Occurs only when `auto exposure` is set to `on`

**Comment by spiralhalo** [comment]
Auto exposure is in the experimental section for a reason. It's just that, an experiment.

**Comment by sharpenedblade** [comment]
I know, bug is there to help get it out of experimental

**Comment by spiralhalo** [comment]
I guess that's a decent point. Just another reason to get rid of this implementation and make a new one. That's how experimental it is.
