### ISSUE TITLE
Green block sides in soul sand valley

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#50]
![2021-05-14_09 58 23](https://user-images.githubusercontent.com/83884198/118304057-04e55100-b49b-11eb-8a3e-6d6bfd93d91a.png)

**Comment by spiralhalo** [comment]
This is intentional. Nether ambient light follows the fog color for historical reason. Feel free to discuss alternative styles but don't classify it as an issue.

**Comment by Reeses-Puffs** [comment]
I remember when this was first being experimented with

**Comment by sharpenedblade** [comment]
I think it should happen to all blocks, and not just the sides, it looks strange
