### ISSUE TITLE
Strange noise pattern with striped flickering

### ISSUE THREAD

**Issue by sharpenedblade** [spiralhalo/LumiLights#52]
A strange noise pattern with striped flickering dots occurs with both blue noise and halton. 

OS: macos 11.2
canvas: lts ver 1501
minecraft: 1.16.5
lumi: 0.25-mac-compat and lumipbrext
java: java 16 adoptopenjdk openj9
mods: `canvas` `modmenu` `litematica` `lazydfu` `amdabettergrass` `fabrishot` `krypton` `dynamic fps` `custom splash screen` `tex tweaks` `wl zoom` `starlight` `antighost` `paperdoll`

config:

[options.txt](https://github.com/spiralhalo/LumiLights/files/6503584/options.txt)

[canvas_pipeline_options.json5.txt](https://github.com/spiralhalo/LumiLights/files/6503589/canvas_pipeline_options.json5.txt)
[canvas.json5.txt](https://github.com/spiralhalo/LumiLights/files/6503590/canvas.json5.txt)

screenshots: 
![2021-05-18_11 37 56](https://user-images.githubusercontent.com/83884198/118707331-3ded3080-b7cf-11eb-9fbe-7a1f01033cd1.png)
![2021-05-18_11 29 57](https://user-images.githubusercontent.com/83884198/118707335-3e85c700-b7cf-11eb-9d18-7335a483346d.png)
![2021-05-18_11 29 53](https://user-images.githubusercontent.com/83884198/118707337-3f1e5d80-b7cf-11eb-85d1-1867c00b4456.png)

Nothing in `.minecraft/canvas_shader_debug`

**Comment by sharpenedblade** [comment]
Happens without any mods but `canvas`,and `fabricapi`.

**Comment by spiralhalo** [comment]
Does this happen with "Half resolution on Macs" turned off in Canvas setting?

**Comment by sharpenedblade** [comment]
>Does this happen with "Half resolution on Macs" turned off in Canvas setting?

yes, and I tried turning off all options, but it still happens

**Comment by asarra** [comment]
> A strange noise pattern with striped flickering dots occurs with both blue noise and halton.

I've had that, too.
Using the release v0.24 fixed it for me.

Might wanna give it a try.

**Comment by sharpenedblade** [comment]
FIxed on git master
