### ISSUE TITLE
Shadows bugged

### ISSUE THREAD

**Issue by CmdrJane** [spiralhalo/LumiLights#53]
So yeah shadows acting weird
Check vid bellow
[Youtube video](https://www.youtube.com/watch?v=-Jd64_2HkTw)

LumiLights ver: v0.25
Mods:
canvas-mc116-1.16-spiralhalo-LTS-1.0.1501
fabric-api-0.33.1+1.16

[DxDiag](https://pastebin.com/gV42zQhM)

**Comment by Reeses-Puffs** [comment]
we know

**Comment by LiSongMWO** [comment]
See: https://github.com/grondag/canvas/issues/278

**Comment by sharpenedblade** [comment]
its almost fixed now

**Comment by Reeses-Puffs** [comment]
I'm pretty sure this shadow issue is resolved by now. Should we close the issue?
