### ISSUE TITLE
Charged creeper effect is black

### ISSUE THREAD

**Issue by jaaaco-j** [spiralhalo/LumiLights#66]
Hi, when using the newest Lumi Lights release on 1.17, the charged creeper effect is black

[here is an image](https://imgur.com/a/ijKzPSF)

**Comment by Reeses-Puffs** [comment]
I dunno man you seem kinda racist

**Comment by jaaaco-j** [comment]
pretty sure that lighning sparks that are giving off light, should not be black

**Comment by spiralhalo** [comment]
Will test. Thanks for the report

**Comment by spiralhalo** [comment]
08370342f872813ae3cf79af8fe441a4015ea22f should fix it
