### ISSUE TITLE
End portal glitching out when selection outline is not visible

### ISSUE THREAD

**Issue by Echo073** [spiralhalo/LumiLights#68]
**Describe the bug:**
...
The end portal renders extremely strangly
**Where/when the bug happens or *doesn't* happen:**
...
The end portals texture glitches out when the selection outline is not on screen. This includes not selecting a block as well as F1
**Screenshots or link to video:**
...
![image](https://user-images.githubusercontent.com/73415306/147038882-0276e6b3-ba43-4420-88de-ff0130a8c4b2.png)
![image](https://user-images.githubusercontent.com/73415306/147038913-0912db79-9c23-4b71-a4bd-4440f4708fab.png)
![image](https://user-images.githubusercontent.com/73415306/147038932-35c3e9d8-3816-44f7-8302-d9d673264368.png)

**Environment:**
- Lumi Lights release version or link to commit: ...
- Canvas debug info from `latest.log` [[see example]](https://github.com/spiralhalo/LumiLights/wiki/Canvas-Debug-Info):
```LumiLights v0.40 snapshot 7
(paste here)
```

**Content of `.minecraft/canvas_shader_debug/failed/` if present (put "N/A" otherwise):**
...

**Additional context:**
...

**Comment by spiralhalo** [comment]
OOOH I know this bug existed but I didn't know it's related to the selection outline! Thanks a lot for this report! I will look into it soon.

**Comment by spiralhalo** [comment]
This should be fixed through https://github.com/vram-guild/canvas/commit/178676942f6fe98be5ad8f97e976d4253f86445e
