### ISSUE TITLE
stars appear during the day with "deep cerulean" sky mode

### ISSUE THREAD

**Issue by Reeses-Puffs** [spiralhalo/LumiLights#70]
**Describe the bug:**
it's in the title

**Where/when the bug happens or *doesn't* happen:**
seems to only happen when deep cerulean is selected

**Screenshots or link to video:**

![2022-02-27_16 02 01](https://user-images.githubusercontent.com/73549793/155899814-bc546942-d3e0-4bc9-8657-563d8617e029.png)

**Environment:**
- Lumi Lights release version or link to commit: latest commit
- Canvas debug info from `latest.log` [[see example]](https://github.com/spiralhalo/LumiLights/wiki/Canvas-Debug-Info):

[latest.log](https://github.com/spiralhalo/LumiLights/files/8149438/latest.log)

**Content of `.minecraft/canvas_shader_debug/failed/` if present (put "N/A" otherwise):**
N/A

**Additional context:**

screenshot was taken at noon

**Comment by spiralhalo** [comment]
Fixed in v0.40
