### ISSUE TITLE
Wrong particles rendering

### ISSUE THREAD

**Issue by 3104NEIL** [spiralhalo/LumiLights#71]
There's some wrong particle rendering while im using LumiLights and the PBR extra.
purple water particles,wrong hit heart particles
![image](https://user-images.githubusercontent.com/93448183/174327833-aa86e04d-e954-49b7-bca5-ac4cb668c823.png)
![image](https://user-images.githubusercontent.com/93448183/174327976-8963c47f-2675-4e00-bd17-258509ea243f.png)
![image](https://user-images.githubusercontent.com/93448183/174328174-ce34c60b-48b4-4d42-8f0b-3150e3f29d09.png)
![image](https://user-images.githubusercontent.com/93448183/174328248-917b8a2f-5265-4ee8-ab13-ec10e552f699.png)

LumiLights 0.40 hotfix1
PBRExt 0.23
CPU AMD Ryzen 5 3500X
GPU AMD Radeon RX 570
...

**Comment by spiralhalo** [comment]
Canvas bug. The more recent version shouldn't have this problem.
