### ISSUE TITLE
Can I share this pack on Minecraft Chinese Forum (mcbbs.net)?

### ISSUE THREAD

**Issue by wstar2022** [spiralhalo/LumiLights#73]
This pack looks good! Can I share this pack on [Minecraft Chinese Forum](https://www.mcbbs.net)? I'll annotate authors and websites. I can also help translate this pack.

**Comment by spiralhalo** [comment]
Thank you! I don't speak Chinese or visit that forum so feel free to do that at your own discretion.

**Comment by sharpenedblade** [comment]
It is completley legal to to share this pack however you want, as long as you release all changes to the source code.
